aspects:
  commitment: Has demonstrated a commitment to fulfill project needs as an employee
  relationships: Builds good working relationships in team and throughout the organization
  working_with_others: Is effective in working with others on collaborative projects
  seeking: Is proactive in seeking out additional work and/or responsibility beyond what is expressly required
  focus: Is able to focus on relevant issues & shows appropriate attention to detail
  understanding: Seeks to understand issues & concerns and develops an appropriate understanding of business and processes
  independence: Shows independence and ability to manage own time effectively
  leadership: Demonstrates leadership qualities appropriate to project scope
  completion: Has completed tasks and demonstrated aptitude in managing project components to their successful completion within the desired timeframe